In [1]:
#arrays

In [15]:
import numpy
a=[10,20,30,40,50]
print(a)
print(a[0])
print(a[3])

[10, 20, 30, 40, 50]
10
40


In [20]:
import numpy
a=[10,20,30,40,50]
x=a[::-1]
c=numpy.array(x)
print(x)

[50, 40, 30, 20, 10]


In [44]:
import numpy
x=numpy.array([10,20,30,40,50,60])
numpy.split(x,2)

[array([10, 20, 30]), array([40, 50, 60])]

In [50]:
import numpy as np
x=np.array([10,20,30,40,50])
tot=0
avg=0
for i in x:
    tot=tot+i
avg=tot/len(x)
print(avg)
    

30.0


In [58]:
import numpy as np
x=np.array([35,10,23,68,40,50])
x.sort()
print(x[-2])

50


In [59]:
import numpy as np
x=np.array([35,10,23,68,40,50])
x.sort()
print(x[0])

10


In [60]:
import numpy as np
x=np.array([35,10,23,68,40,50])
x.sort()
print(x[-1])

68


In [68]:
import numpy as np
x=np.array([35,10,23,68,40,50])
print(len(x))


6


In [82]:
import numpy as np
x=np.array([35,10,23,68,40,50])
a=x[::2]
b=x[1::2]
print("even position :",a)
print("odd position :",b)

even position : [35 23 40]
odd position : [10 68 50]


In [87]:
import numpy as np
x=np.array([35,10,23,68,40,50])
print(x[2:3])

[23]


In [95]:
import numpy as np
x=np.array([35,10,23,68,40,50])
np.delete(x,2)

array([35, 10, 68, 40, 50])

In [96]:
import numpy as np
x=np.array([35,10,23,68,40,50])
a=list(x)
print(a)

[35, 10, 23, 68, 40, 50]


In [1]:
import numpy as np
x=np.array([35,10,23,68,40,50])
a=len(x)
print(a)

6


In [2]:
import numpy as np
x=np.array([35,10,23,68,40,50])
print(x[::-1])

[50 40 68 23 10 35]


In [13]:
import numpy as np
x=np.array([35,10,23,68,40,50])
a=np.append(x,[12])
print(a)

[35 10 23 68 40 50 12]
